feign:
  url:
    user: http://localhost:8000
    course: http://localhost:8100
    course-content: http://localhost:8200
    enrollment: http://localhost:8300
    notification: http://localhost:7000
    payment: http://localhost:3000
